# Generated by Django 5.2.4 on 2025-07-23 11:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capp", "0002_alter_member_options_alter_member_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["position"]},
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("user", "position")},
        ),
    ]
