# Generated by Django 5.1.2 on 2025-07-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together=set(),
        ),
    ]
