"""
Django settings for cricpro project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-da^tfo2o_2lfuh^^eii3lv4j#_k7%7e9voeeh3p4-)@&^3uah$"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# ALLOWED_HOSTS = [
#     'srihari453.pythonanywhere.com',
#     'localhost',
#     '127.0.0.1',
# ]
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',
    "capp",
    'widget_tweaks',
    'mathfilters',
    'allauth',
    'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "cricpro.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'capp.context_processors.live_matches_context',
            ],
        },
    },
]

WSGI_APPLICATION = "cricpro.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'srihari453$cricket_db',  # or 'srihari453$capp_member'
#         'USER': 'srihari453',
#         'PASSWORD': 'Akhil@123',  # set in the Databases tab
#         'HOST': 'srihari453.mysql.pythonanywhere-services.com',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",}

#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"



# Database timezone settings
USE_TZ = True
TIME_ZONE = 'Asia/Kolkata'

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"



DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/login/'
# LOGIN_URL = '/accounts/login/'


# # Add after INSTALLED_APPS
# SITE_ID = 1

# # Authentication backends
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     'allauth.account.auth_backends.AuthenticationBackend',
# ]
# ACCOUNT_FORMS = {
#     'login': 'capp.forms.CustomLoginForm',
#     'signup': 'capp.forms.CustomSignupForm',
# }
# # Allauth settings
# # With these new settings:
# ACCOUNT_LOGIN_METHODS = {'username', 'email'}
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'username', 'password1*', 'password2*']
# ACCOUNT_EMAIL_VERIFICATION = 'optional'
# ACCOUNT_SESSION_REMEMBER = True
# ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

# # # Social account providers
# # SOCIALACCOUNT_PROVIDERS = {
# #     'google': {
# #         'SCOPE': [
# #             'profile',
# #             'email',
# #         ],
# #         'AUTH_PARAMS': {
# #             'access_type': 'online',
# #         },
# #         'OAUTH_PKCE_ENABLED': True,
# #     }
# # }

# # Keep your existing login settings
# LOGIN_REDIRECT_URL = '/'
# # LOGOUT_REDIRECT_URL = '/accounts/login/'
# # LOGIN_URL = '/accounts/login/'


# # Social Account Providers
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         },
#         'APP': {
#             'client_id': '536448435529-9tnobihagtc2cbdda3dmagf3bvjl-apps.googleusercontent.com',
#             'secret': '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',
#             'key': ''
#         }
#     }
# }

# # Required settings
# ACCOUNT_LOGOUT_REDIRECT_URL = '/'
# SOCIALACCOUNT_LOGIN_ON_GET = True
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

# Allauth Configuration
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Account settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_SESSION_REMEMBER = True

# URL settings
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

# Social account settings
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

# Remove the APP section from SOCIALACCOUNT_PROVIDERS
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}
